// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvppqdixnkqqjqcdudym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2cHBxZGl4bmtxcWpxY2R1ZHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzMjc4NTgsImV4cCI6MjA5MTkwMzg1OH0.03BQMz-szptcebmHNUqH17d09OnCJc25Wq7_ugr4nms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});